trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
 pipelines:
   - pipeline: mySourcePipeline
     source: shubhamkarnwal.azure-devops-test2
     project: shubhamkarnwal
     trigger: true

steps:
- script: echo Pipeline details
  displayName: 'Run a one-line script'
