trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
 pipelines:
   - pipeline: pipeline1
     source: pipeline1
     trigger: true

steps:
- script: echo Pipeline details '${{ resources.pipeline.pipeline1.pipelineID }}'
  displayName: 'Run a one-line script'
