trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
 pipelines:
   - pipeline: mySourceTriggerPipeline
     source: shubhamkarnwal.azure-devops-test1
     trigger: true

steps:
- script: echo Pipeline details
  displayName: 'Run a one-line script'
